name: Publish new release
on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: manifest Version
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: version
          VALUE: ${{steps.tag.outputs.tag}}
          FILE: manifest.json

      - name: web-ext build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .

      - name: save output filename to env var
        run: echo "ARTIFACT_FILENAME=$(basename ${{steps.web-ext-build.outputs.target}})" >> $GITHUB_ENV

      - name: save the artifact for the release jobs
        uses: actions/upload-artifact@v3
        with:
          name: extension-artifact
          path: ${{ steps.web-ext-build.outputs.target }}

  release-firefox:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: get the artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-artifact

      - name: publish Firefox extension
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: ecosia-keyboard-shortcuts
          xpi-path: ${{ env.ARTIFACT_FILENAME }}
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_SECRET }}

  release-chrome:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: get the artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-artifact

      - name: publish Chrome extension
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish'
          client_id: ${{ secrets.CHROME_CLIENT }}
          client_secret: ${{ secrets.CHROME_SECRET }}
          refresh_token: ${{ secrets.CHROME_TOKEN }}
          extension_id: 'dpobhneijjdebjccapdmeflhegkjfeij'
          zip_file: ${{ env.ARTIFACT_FILENAME }}
